baseURL = "/"
title = "Ben Fox, Consultant"
theme = "hugo-orbit-theme"
DateForm = "Mon, 2. Jan. 2006"

[params]

  [params.profile]
  name = "Ben Fox"
  tagline = "Certified Autism Specialist"

  [params.contact]

    [[params.contact.list]]
    class = "email"
    icon = "fa-envelope"
    url = "mailto: yourname@email.com"
    title = "john.doe@website.com"

  [params.pages]
  disableKinds = [
    "sitemap"
  ]

    [[params.pages.index]]
    Section = "Intro"
    partial = "index/intro.html"

    [[params.pages.sidebar]]
    Section = "Profile"
    partial = "sidebar/profile.html"

    [[params.pages.sidebar]]
    Section = "Contact"
    partial = "sidebar/contact.html"

    [[params.pages.sidebar]]
    Section = "Education"
    partial = "sidebar/education.html"
