baseurl = "/"
languageCode = "en-us"
title = "benfox.net"
theme = "hugo-story-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	[params.about]
		hide  = false
		style = "1"
		title = "Hello, my name<br />is Ben Fox"
		content = "I am a <a href="https://apps.ibcces.org/badges/v/65d52" target="_blank">Certified Autism Specialist</a> offering professional consulting services to families, schools, community organizations, and service providers to help develop social skills education programs to serve the needs of children and young adults with ASDs in Eastern Washington."
		image = "about/benfox.jpg"
		orientation = "left"


		[[params.about.blurb]]
		style = "1"
		title = "In 2005 I began my consulting</br>career in New York..."
		content = "where I helped kickstart a collaboration between District 75 and <a href="http://www.grasp.org" target="_blank">G.R.A.S.P.</a>, an organization dedicated to providing peer-based supports to people on the Autism Spectrum. After the success of this pilot program, I spent the next few years providing training and staff support to teachers and administrators throughout the NYC Public Schools System. Some of this work has been profiled in an <a href="http://reader.mediawiremobile.com/epmagazine/issues/203090/viewer?page=21" target="_blank">Exceptional Parent Magazine</a> article highlighting the benefits of peer support groups in schools."
		image = "about/nyc.jpg"
		orientation = "right"

		[[params.about.blurb]]
		style = "1"
		title = "That same year I started my</br>Private Practice in Brooklyn..."
		content = "where I combined the successes of peer-based social skills programs with research-based ABA and Floortime methodologies to develop inclusive <b>Facilitated Social Play</b> programs, where children with Autism or other social learning disorders can learn from "social expert" peers through play. These sessions are facilitated by professionals with advanced Autism training and experience with other complementary interventions. My role is to provide ongoing training, playspace design, program, and professional development to help transform experts accustomed to intensive, 1-on-1 therapeutic settings, into community organizers and volunteer recruiters. I have consulted and worked with families, in-home service providers, private schools and early intervention centers, to help build successful programs <i>and meaningful friendships</i> for children with ASD, that have lasted and grown with them for years."
		image = "about/playground.jpg"
		orientation = "left"


		[[params.about.blurb]]
		style = "1"
		title = "And now I am offering my skills and services to the families and communities of the Pacific Northwest"
		content = "After living and farming in the Tri-Cities for years I have relaunched my practice to better meet the needs of the surrounding communities. In addition to providing training, seminars, consulting and program development for Facilitated Social Play groups, I am also seeking opportunities to collaborate with local schools and community organizations to build innovative, inclusive programs to help children and young adults with Autism find their Awesome."
		image = "about/tricities.jpg"
		orientation = "right"


	[params.portfolio]
		hide  = true
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0
